version: "3.9"

services:
  weather-system-analysis:
    build:
      context: .
      dockerfile: Dockerfile
    image: weather_system
    restart: always
    volumes:
      - .:/weather_system/
    command: >
      sh -c "python3 manage.py showmigrations &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "9049:8000"
    container_name: weather-system-analysis

    depends_on:
      - weather_db
    stdin_open: true
    tty: true

  weather_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Pa55word!
      POSTGRES_DB: weather_analysis
    ports:
      - "5434:5432"
    container_name: weather_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: